### ISSUE TITLE
Resource name changes

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-devnet-api#62]
For consistency with our other services, can we update some resource names? Here are some suggestions that would make us aligned with our other infra.

# Pods
* change `stacks-api` to `stacks-blockchain-api`
* change `stacks-node` to `stacks-blockchain`

# Containers
* Exclude -container suffix where applicable
* Update container names to match the repository/project they came from (e.g. stacks-api-container > stacks-blockchain-api, stacks-api-postgres > postgres, etc)

# Services
* Service names should match the pod they're routing traffic to (e.g. `stacks-api-service` would change to `stacks-blockchain-api`)

# PVC
* `stacks-api-pvc` should change to `stacks-blockchain-api-pg`

# Configmap
* Exclude `-conf` suffix where applicable
* I think the `namespace-conf` CM can be replaced with a slight change in the bitcoind container.
    * If you add this to the `env:` section of the bitcoind container definition, you won't need this CM anymore.
    ```
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    ```
* Update stacks-api-conf to stacks-blockchain-api
* Update stacks-api-postgres-conf to stacks-blockchain-api-pg
* Update stacks-node-conf to stacks-blockchain
